### ISSUE TITLE
Bounds issues with Java 14

### ISSUE THREAD

**Issue by jshiell** [eclipse-ee4j/orb-gmbal#22]
We're using the Glassfish ORB with GMBAL 4.0.1 (4.0.0 shows the same behaviour). The ORB is fine with Java 11; however, upon switching the runtime to Java 14+36 we see the following on registering the ORB:
```
java.lang.UnsupportedOperationException: WARNING: GMBALTLIB00004: Multiple upper bounds not supported on S
	at com.sun.proxy.$Proxy54.multipleUpperBoundsNotSupported(Unknown Source)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.lookup(TypeEvaluator.java:632)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitTypeVariable(TypeEvaluator.java:573)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.evaluateType(TypeEvaluator.java:397)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitMethodDeclaration(TypeEvaluator.java:554)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.access$600(TypeEvaluator.java:372)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:716)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:712)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:70)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:93)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.processClass(TypeEvaluator.java:710)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.getCorrectDeclaration(TypeEvaluator.java:668)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitClassDeclaration(TypeEvaluator.java:445)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.evaluateType(TypeEvaluator.java:391)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$1.evaluate(TypeEvaluator.java:537)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$1.evaluate(TypeEvaluator.java:535)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:70)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:93)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitMethodDeclaration(TypeEvaluator.java:534)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.access$600(TypeEvaluator.java:372)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:716)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:712)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:70)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:93)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.processClass(TypeEvaluator.java:710)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.getCorrectDeclaration(TypeEvaluator.java:668)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitClassDeclaration(TypeEvaluator.java:445)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.evaluateType(TypeEvaluator.java:391)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitMethodDeclaration(TypeEvaluator.java:554)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.access$600(TypeEvaluator.java:372)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:716)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:712)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:70)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:93)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.processClass(TypeEvaluator.java:710)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.getCorrectDeclaration(TypeEvaluator.java:668)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitClassDeclaration(TypeEvaluator.java:445)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.evaluateType(TypeEvaluator.java:391)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$2.evaluate(TypeEvaluator.java:694)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$2.evaluate(TypeEvaluator.java:692)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:70)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:93)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.processClass(TypeEvaluator.java:691)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.getCorrectDeclaration(TypeEvaluator.java:668)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitClassDeclaration(TypeEvaluator.java:445)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.evaluateType(TypeEvaluator.java:391)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitMethodDeclaration(TypeEvaluator.java:554)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.access$600(TypeEvaluator.java:372)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:716)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:712)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:70)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:93)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.processClass(TypeEvaluator.java:710)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.getCorrectDeclaration(TypeEvaluator.java:668)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitClassDeclaration(TypeEvaluator.java:445)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.evaluateType(TypeEvaluator.java:391)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitMethodDeclaration(TypeEvaluator.java:554)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.access$600(TypeEvaluator.java:372)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:716)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:712)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:70)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:93)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.processClass(TypeEvaluator.java:710)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.getCorrectDeclaration(TypeEvaluator.java:668)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitClassDeclaration(TypeEvaluator.java:445)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.evaluateType(TypeEvaluator.java:391)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitMethodDeclaration(TypeEvaluator.java:554)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.access$600(TypeEvaluator.java:372)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:716)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:712)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:70)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:93)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.processClass(TypeEvaluator.java:710)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.getCorrectDeclaration(TypeEvaluator.java:668)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitClassDeclaration(TypeEvaluator.java:445)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.evaluateType(TypeEvaluator.java:391)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$2.evaluate(TypeEvaluator.java:694)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$2.evaluate(TypeEvaluator.java:692)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:70)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:93)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.processClass(TypeEvaluator.java:691)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.getCorrectDeclaration(TypeEvaluator.java:668)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitClassDeclaration(TypeEvaluator.java:445)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.evaluateType(TypeEvaluator.java:391)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$2.evaluate(TypeEvaluator.java:694)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$2.evaluate(TypeEvaluator.java:692)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:70)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:93)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.processClass(TypeEvaluator.java:691)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.getCorrectDeclaration(TypeEvaluator.java:668)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitClassDeclaration(TypeEvaluator.java:445)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.evaluateType(TypeEvaluator.java:391)
	at org.glassfish.gmbal.typelib.TypeEvaluator.getEvaluatedType(TypeEvaluator.java:285)
	at org.glassfish.gmbal.impl.ManagedObjectManagerImpl.constructMBean(ManagedObjectManagerImpl.java:619)
	at org.glassfish.gmbal.impl.MBeanTree.setRoot(MBeanTree.java:72)
	at org.glassfish.gmbal.impl.ManagedObjectManagerImpl.createRoot(ManagedObjectManagerImpl.java:414)
	at com.sun.corba.ee.spi.orb.ORB.createORBManagedObjectManager(ORB.java:685)
	at com.sun.corba.ee.impl.orb.ORBImpl.initManagedObjectManager(ORBImpl.java:364)
	at com.sun.corba.ee.impl.orb.ORBImpl.postInit(ORBImpl.java:544)
	at com.sun.corba.ee.impl.orb.ORBImpl.set_parameters(ORBImpl.java:667)
	at org.omg.CORBA.ORB.init(ORB.java:359)
	at com.coremedia.cotopaxi.corba.CorbaConnectStrategy.initORB(CorbaConnectStrategy.java:304)
```
The cause seems to be the following method signature in `java.net.SocketImpl`, where it really does not like the multiple upper bounds:
```
static <S extends SocketImpl & PlatformSocketImpl> S createPlatformSocketImpl(boolean server)
```

**Comment by 7thbit-com** [comment]
Is this under investigation? We have the same issue with JAVA 14 runtime.

**Comment by ahubold** [comment]
Same problem here with Java 15.

**Comment by arjantijms** [comment]
Same problem of course with Java 16. That `createPlatformSocketImpl` method will not likely go away soon.

We should probably investigate how to exactly handle this. The TypeEvaluator contains this code:

```java
 private EvaluatedType lookup( TypeVariable tvar ) {
            EvaluatedType result = null ;

            try {
                result = display.lookup( tvar.getName() ) ;

                if (result == null) {
                    Type[] bounds = tvar.getBounds() ;
                    if (bounds.length > 0) {
                        if (bounds.length > 1) {
                            throw Exceptions.self
                                .multipleUpperBoundsNotSupported( tvar ) ;
                        }

                        result = evaluateType( bounds[0] ) ;
                    }
```

Here those two bounds would be:

* class `java.net.SocketImpl`
* interface `sun.net.PlatformSocketImpl`

Eventually that evaluated type would end up as a parameter here:

```java
DeclarationFactory.emdecl(
   cdecl, 
   mdecl.getModifiers(),
   // mdecl here would be the method
   // static java.net.SocketImpl java.net.SocketImpl.createPlatformSocketImpl(boolean)
   evaluateType(mdecl.getGenericReturnType()), 
   mdecl.getName(), 
   eptypes, mdecl ) ;
```

A quick fix could be to evaluate both bounds, but only return the first one, maybe via a switch of some kind.

Actually handling multiple returns types very quickly cascades to pretty much everywhere, as tons of places need to be adjusted to take into account multiple return types, and unless you're very deep into the internals of gmbal it's no so clear what to actually do with multiple returns at all those places.

**Comment by arjantijms** [comment]
For if it helps anyone, this is the commit introducing the exception on multiple bounds:

https://github.com/javaee/gmbal/commit/1220f4b790186595cf3861c66436c23a7eb2ee94

**Comment by smillidge** [comment]
Should be fixed by #22 and setting the System Property. @arjantijms can you confirm?

**Comment by arjantijms** [comment]
Should be fixed indeed, I tested up to Java 16.

**Comment by jshiell** [comment]
Looks good here - thanks very much folks!

**Comment by oliva123456** [comment]
> 
> 
> Should be fixed by #22 and setting the System Property. @arjantijms can you confirm?

just for the case, that someone else is curious about setting 'the' mentioned system property -it is: org.glassfish.gmbal.no.multipleUpperBoundsException=true

taken from: https://github.com/eclipse-ee4j/orb-gmbal/commit/0fb19f45fcb1b70a3e4b668bda3d0ad2f3cbdc46

thanks for providing the fix !

**Comment by arjantijms** [comment]
You're welcome! Btw, it's now also tested with JDK 17 on a regular basis.

**Comment by oguzhansng** [comment]
Same problem here with Java 21 is there any solution ?

**Comment by dmatej** [comment]
> Same problem here with Java 21 is there any solution ?

As it is mentioned in comments here, you can run your application with this system property:
`-Dorg.glassfish.gmbal.no.multipleUpperBoundsException=true`
